services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d demo"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8083:8080"
    depends_on:
      - postgres

  activemq:
    image: vromero/activemq-artemis:latest
    container_name: activemq
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=admin
      - JAVA_ARGS=-Djava.net.preferIPv4Stack=true
    ports:
      - "61616:61616"  # JMS
      - "8161:8161"    # Web console
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 61616 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  order-manager:
    build: ./order-manager
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    depends_on:
      activemq:
        condition: service_started
      postgres:
        condition: service_healthy

  delivery-tracker:
    build: ./delivery-tracker
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    depends_on:
      activemq:
        condition: service_started
      postgres:
        condition: service_healthy

volumes:
  pgdata:
  activemq-data: