version: "3.9"
services:
  activemq:
    image: quay.io/artemiscloud/activemq-artemis-broker:latest
    environment:
      - AMQ_USER=admin
      - AMQ_PASSWORD=admin
      - AMQ_ACCEPTORS=artemis
    ports:
      - "8161:8161"    # console
      - "61616:61616"  # JMS

  order-manager:
    build: ./order-manager
    ports:
      - "8085:8080"    # <- évite collision 8081 si déjà pris
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    depends_on:
      - activemq        # simple (pas de healthcheck)

  delivery-tracker:
    build: ./delivery-tracker
    ports:
      - "8086:8080"    # <- évite collision 8082 si déjà pris
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    depends_on:
      - activemq
