services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d demo"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8083:8080"
    depends_on:
      - postgres
      
  activemq:
    image: quay.io/artemiscloud/activemq-artemis-broker:latest
    environment:
      - AMQ_USER=admin
      - AMQ_PASSWORD=admin
      - AMQ_ACCEPTORS=artemis
    ports:
      - "8161:8161"     # console
      - "61616:61616"   # JMS

  order-manager:
    build: ./order-manager
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    depends_on:
      activemq:
        condition: service_started
      postgres:
        condition: service_healthy

  delivery-tracker:
    build: ./delivery-tracker
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
    depends_on:
      activemq:
        condition: service_started
      postgres:
        condition: service_healthy

volumes:
  pgdata: