spring:
  artemis:
    broker-url: ${ACTIVEMQ_BROKER_URL:tcp://activemq:61616}
    user: admin
    password: admin

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:demo}
    username: ${DB_USER:demo}
    password: ${DB_PASSWORD:demo}
    driver-class-name: org.postgresql.Driver
    embedded-database-connection: none
    hikari:
      data-source-properties:
        ApplicationName: order-manager

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: delivery_tracker
        format_sql: true

  flyway:
    enabled: true
    default-schema: delivery_tracker
    schemas: delivery_tracker
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true