spring:
  datasource:
    url: jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true  # autorise l’accès depuis l’hôte (docker)
  jms:
    template:
      default-destination: queue.orders.new

environment:
  - SPRING_PROFILES_ACTIVE=docker
  - ACTIVEMQ_BROKER_URL=tcp://activemq:61616

server:
  port: 8080
  servlet:
    session:
      timeout: 2h
      cookie:
        http-only: true
        same-site: Lax
        name: ORDERSESSIONID

logging:
  pattern:
    level: "%5p [corrId=%X{corrId}]"

